# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - script: |
      python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'

  - script: |
      pip install -e.[dev]
    displayName: "Setup"

  - script: |
      pytest
    displayName: "Test"

  - script: |
      pip install bump twine
      bump
      python setup.py sdist
      python -m twine upload -u __token__ -p $(TWINE_PASSWORD) --skip-existing dist/*
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: "Deploy to PyPI"
